In [0]:
ls=[1,2,3]
print(ls)

[1, 2, 3]


In [0]:
import numpy as np
a=np.array(ls)
print(a)

[1 2 3]


In [0]:
print(type(a))

<class 'numpy.ndarray'>


In [0]:
a=np.append(a,[50,70])
print(a)

[ 1  2  3 50 70]


In [0]:
a=np.array([1,2,3])
print(a)
newarray=np.insert(a,1,100)
print(newarray)

[1 2 3]
[  1 100   2   3]


In [0]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[400],[800]])
newarray=np.append(a,b,axis=1)
print(newarray)

[[  1   2   3 400]
 [  4   5   6 800]]


In [0]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[400],[800]])
newarray=np.append(a,b)
print(newarray)

[  1   2   3   4   5   6 400 800]


In [0]:
a=np.array([[1,2,3],[4,5,6]])
a[0][1]

2

In [0]:
a[1][2]

6

In [0]:
a[:,1:2]

array([[2],
       [5]])

In [0]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
a[:,0:1]

array([[1],
       [4]])

In [0]:
a[:,0:2]

array([[1, 2],
       [4, 5]])

In [0]:
a[:,:]

array([[1, 2, 3],
       [4, 5, 6]])

In [0]:
b=a>2
b

array([[False, False,  True],
       [ True,  True,  True]])

In [0]:
c=a<5
c

array([[ True,  True,  True],
       [ True, False, False]])

In [0]:
a[a<=2]=1
a[a>2]=0
a

array([[1, 1, 1],
       [1, 1, 1]])

In [0]:
a=np.array([[10,20,30],[40,50,60]])
for i in a:
  for j in range(len(i)):
    print(i[j])

10
20
30
40
50
60


In [0]:
a=np.array([1,2,4,6,6,3,6])
print(np.where(a==6))


(array([3, 4, 6]),)


In [0]:
a.shape

(7,)

In [0]:
c=np.array([1,5,6,3,8,9])
b=c>3
b

array([False,  True,  True, False,  True,  True])

In [0]:
x=np.array([1,2,3])
np.concatenate([a,x])



array([1, 2, 4, 6, 6, 3, 6, 1, 2, 3])

In [0]:
x=np.array([60,100,50,70,80,90])
sorted_array=np.sort(x)
sorted_array

array([ 50,  60,  70,  80,  90, 100])

In [0]:
x.mean()

75.0

In [0]:
x.max()

100